[tool.poetry]
name = "new-arrivals-chi"
version = "0.1.0"
description = ""
authors = ["Aaron Haefner <aaronhaefner@uchicago.edu>"]
readme = "README.md"
packages = [{include = "new_arrivals_chi"}]

[tool.poetry.dependencies]
python = "^3.9"
pre-commit = "^3.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
