"""Relationships fix.

Revision ID: 6e1f62d7980b
Revises: 157b362584d8
Create Date: 2024-05-01 13:53:50.296328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e1f62d7980b"
down_revision = "157b362584d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.drop_constraint("locations_org_id_fkey", type_="foreignkey")
        batch_op.drop_column("org_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "org_id", sa.INTEGER(), autoincrement=False, nullable=False
            )
        )
        batch_op.create_foreign_key(
            "locations_org_id_fkey", "organizations", ["org_id"], ["id"]
        )

    # ### end Alembic commands ###
