"""Change primary location to boolean

Revision ID: 157b362584d8
Revises: d3cd733bc032
Create Date: 2024-04-30 14:10:22.625040

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "157b362584d8"
down_revision = "d3cd733bc032"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.execute(
            """
            ALTER TABLE locations 
            ALTER COLUMN primary_location TYPE BOOLEAN 
            USING CASE WHEN primary_location = 0 THEN FALSE ELSE TRUE END
        """
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.execute(
            """
            ALTER TABLE locations 
            ALTER COLUMN primary_location TYPE INTEGER 
            USING CASE WHEN primary_location THEN 1 ELSE 0 END
        """
        )

    # ### end Alembic commands ###
