"""Adding created_by, deleted_by, created_at and deleted_at columns.

Revision ID: 56a8e2512e2b
Revises: 16cf46fcdfbf
Create Date: 2024-04-26 17:04:24.926570

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "56a8e2512e2b"
down_revision = "16cf46fcdfbf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hours", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("created_by", sa.Integer(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("deleted_by", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(None, "users", ["created_by"], ["id"])
        batch_op.create_foreign_key(None, "users", ["deleted_by"], ["id"])

    with op.batch_alter_table("languages", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("created_by", sa.Integer(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("deleted_by", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(None, "users", ["created_by"], ["id"])
        batch_op.create_foreign_key(None, "users", ["deleted_by"], ["id"])

    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("created_by", sa.Integer(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("deleted_by", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(None, "users", ["deleted_by"], ["id"])
        batch_op.create_foreign_key(None, "users", ["created_by"], ["id"])

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("created_by", sa.Integer(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("updated_by", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(None, "users", ["created_by"], ["id"])
        batch_op.create_foreign_key(None, "users", ["updated_by"], ["id"])

    with op.batch_alter_table("service_dates", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("created_by", sa.Integer(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("deleted_by", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(None, "users", ["created_by"], ["id"])
        batch_op.create_foreign_key(None, "users", ["deleted_by"], ["id"])

    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("created_by", sa.Integer(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("deleted_by", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(None, "users", ["created_by"], ["id"])
        batch_op.create_foreign_key(None, "users", ["deleted_by"], ["id"])

    role_type = sa.Enum(
        "admin", "standard", name="role_types", create_type=True
    )
    role_type.create(op.get_bind(), checkfirst=True)

    # Continue with other modifications
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "role",
                sa.Enum("admin", "standard", name="role_types"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("role")

    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("deleted_by")
        batch_op.drop_column("created_by")
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("service_dates", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("deleted_by")
        batch_op.drop_column("created_by")
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("updated_by")
        batch_op.drop_column("created_by")
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("deleted_by")
        batch_op.drop_column("created_by")
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("languages", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("deleted_by")
        batch_op.drop_column("created_by")
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("hours", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("deleted_by")
        batch_op.drop_column("created_by")
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
