"""empty message.

Revision ID: feba3a15cf10
Revises: 65ad78872dbb
Create Date: 2024-05-15 20:10:24.355637

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "feba3a15cf10"
down_revision = "65ad78872dbb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hours", schema=None) as batch_op:
        batch_op.alter_column(
            "created_by", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("languages", schema=None) as batch_op:
        batch_op.alter_column(
            "created_by", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("neighborhood", sa.String(length=100), nullable=False)
        )
        batch_op.alter_column(
            "created_by", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=260),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "location_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "hours_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "created_by", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("service_dates", schema=None) as batch_op:
        batch_op.alter_column(
            "created_by", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.alter_column(
            "created_by", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.alter_column(
            "created_by", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("service_dates", schema=None) as batch_op:
        batch_op.alter_column(
            "created_by", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.alter_column(
            "created_by", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "hours_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "location_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=260),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False,
        )

    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.alter_column(
            "created_by", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.drop_column("neighborhood")

    with op.batch_alter_table("languages", schema=None) as batch_op:
        batch_op.alter_column(
            "created_by", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("hours", schema=None) as batch_op:
        batch_op.alter_column(
            "created_by", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###
