"""Many to many relationships

Revision ID: d3cd733bc032
Revises: 1e3c8e6e7d23
Create Date: 2024-04-29 23:43:56.948243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3cd733bc032"
down_revision = "1e3c8e6e7d23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_dates_services",
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("service_date_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_date_id"],
            ["service_dates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("service_id", "service_date_id"),
    )
    with op.batch_alter_table("service_dates", schema=None) as batch_op:
        batch_op.drop_constraint(
            "service_dates_service_id_fkey", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "service_dates_org_id_fkey", type_="foreignkey"
        )
        batch_op.drop_column("org_id")
        batch_op.drop_column("service_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_dates", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "service_id", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "org_id", sa.INTEGER(), autoincrement=False, nullable=False
            )
        )
        batch_op.create_foreign_key(
            "service_dates_org_id_fkey", "organizations", ["org_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "service_dates_service_id_fkey", "services", ["service_id"], ["id"]
        )

    op.drop_table("service_dates_services")
    # ### end Alembic commands ###
