"""Location services fix

Revision ID: 923816bbaeb7
Revises: 6e1f62d7980b
Create Date: 2024-05-01 15:23:03.998720

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "923816bbaeb7"
down_revision = "6e1f62d7980b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_services",
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("location_id", "service_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("location_services")
    # ### end Alembic commands ###
